artifact_uri: file:///Users/davideferreri/Documents/GitHub/ML-and-AI/supervised-learning/renewable-energy-forecast/mlflow_data/935902091178395210/dfc4f84355484f2f92e3ebde936d968f/artifacts
end_time: 1768194958039
entry_point_name: ''
experiment_id: '935902091178395210'
lifecycle_stage: active
run_id: dfc4f84355484f2f92e3ebde936d968f
run_name: peaceful-gull-200
source_name: ''
source_type: 4
source_version: ''
start_time: 1768194952268
status: 3
tags: []
user_id: davideferreri
