artifact_location: file:///Users/davideferreri/Documents/GitHub/ML-and-AI/supervised-learning/renewable-energy-forecast/mlflow_data/935902091178395210
creation_time: 1768194951790
experiment_id: '935902091178395210'
last_update_time: 1768194951790
lifecycle_stage: active
name: Solar_Power_Forecasting
